using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace CefDotnet.CefApi.Types;

///
/// Key event types.
///
public enum cef_key_event_type_t
{
    ///
    /// Notification that a key transitioned from "up" to "down".
    ///
    KEYEVENT_RAWKEYDOWN = 0,

    ///
    /// Notification that a key was pressed. This does not necessarily correspond
    /// to a character depending on the key and language. Use KEYEVENT_CHAR for
    /// character input.
    ///
    KEYEVENT_KEYDOWN,

    ///
    /// Notification that a key was released.
    ///
    KEYEVENT_KEYUP,

    ///
    /// Notification that a character was typed. Use this for text input. Key
    /// down events may generate 0, 1, or more than one character event depending
    /// on the key, locale, and operating system.
    ///
    KEYEVENT_CHAR
}

///
/// Structure representing keyboard event information.
///
[StructLayout(LayoutKind.Sequential)]
public unsafe struct cef_key_event_t
{
    public cef_key_event_t()
    {
        size = (nuint)sizeof(cef_key_event_t);
    }

    ///
    /// Size of this structure.
    ///
    nuint size;

    ///
    /// The type of keyboard event.
    ///
    public cef_key_event_type_t type;

    ///
    /// Bit flags describing any pressed modifier keys. See
    /// cef_event_flags_t for values.
    ///
    public uint modifiers;

    ///
    /// The Windows key code for the key event. This value is used by the DOM
    /// specification. Sometimes it comes directly from the event (i.e. on
    /// Windows) and sometimes it's determined using a mapping function. See
    /// WebCore/platform/chromium/KeyboardCodes.h for the list of values.
    ///
    public int windows_key_code;

    ///
    /// The actual key code genenerated by the platform.
    ///
    public int native_key_code;

    ///
    /// Indicates whether the event is considered a "system key" event (see
    /// http://msdn.microsoft.com/en-us/library/ms646286(VS.85).aspx for details).
    /// This value will always be false on non-Windows platforms.
    ///
    public int is_system_key;

    ///
    /// The character generated by the keystroke.
    ///
    public ushort character;

    ///
    /// Same as |character| but unmodified by any concurrently-held modifiers
    /// (except shift). This is useful for working out shortcut keys.
    ///
    public ushort unmodified_character;

    ///
    /// True if the focus is currently on an editable field on the page. This is
    /// useful for determining if standard key events should be intercepted.
    ///
    int focus_on_editable_field;
}